testsuite/smokey/y2038: replace gettid() function with a wrapper of __NR_gettid system call
It fails to build testsuite/smokey/y2038 because there is no gettid() function
in earlier glibc than 2.30. The commit that added gettid() function to glibc
can be found at [1].

The following build failure is detected when using glibc 2.27 on Ubuntu
18.04.6 LTS (Bionic Beaver):

syscall-tests.c: In function ‘test_sc_cobalt_timer_settime64’:
syscall-tests.c:1211:31: error: implicit declaration of function ‘gettid’; did you mean ‘getgid’? [-Werror=implicit-function-declaration]
  sev.sigev_notify_thread_id = gettid();
                               ^~~~~~
                               getgid

[1] https://sourceware.org/git/?p=glibc.git;a=commit;h=1d0fc213824eaa2a8f8c4385daaa698ee8fb7c92

Signed-off-by: Ethan <aspirestro@163.com>
Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>