testsuite/smokey/sched-quota: Allow building with gcc 12
The build with gcc 12 failed with two overflow warnings. gcc is
stricter in checking specifier overflows now.

In this case "t%d" requires up to 12 characters but only 8 were
available.

The warning:

sched-quota.c: In function ‘calibrate’:
sched-quota.c:244:34: error: ‘%d’ directive writing between 1 and 10 bytes into a region of size 7 [-Werror=format-overflow=]
  244 |                 sprintf(label, "t%d", n);
      |                                  ^~
sched-quota.c:244:32: note: directive argument in the range [0, 2147483646]
  244 |                 sprintf(label, "t%d", n);
      |                                ^~~~~
sched-quota.c:244:17: note: ‘sprintf’ output between 3 and 12 bytes into a destination of size 8
  244 |                 sprintf(label, "t%d", n);

Fixed by extending the label/buffer space. In addition the migration to
snprintf avoids a buffer overflow.

Signed-off-by: Florian Bezdeka <florian.bezdeka@siemens.com>
Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>