rt_e1000e: Fix __bad_udelay linking error
This is similar to upstream commit 9e6c3b63399dd ("e1000e: fix compiler
warnings" by David Ertman). Fix compile error:

  ERROR: "__bad_udelay" [drivers/xenomai/net/drivers/e1000e/rt_e1000e.ko] undefined!

Signed-off-by: Vitaly Chikunov <vt@altlinux.org>
Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>