lib/boilerplate: Convert pthread_mutexattr_setrobust_np stub into inline function
Recent glibc (at leasst 2.34) triggers

  CC       libposix_fork_a-posix-fork.o
In file included from posix-fork.c:11:
../../../include/boilerplate/libc.h:248:10: error: expected identifier or '(' before '{' token
  248 |         ({ ENOSYS; })
      |          ^

So switch to a static inline, like for all the other stubs.

Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>