y2038: testsuite/clocktest: Fix link compile error observed on Debian 13
The following build failure was detected on Debian sid/trixie:

clocktest.c: In function ‘read_reference_clock’:
clocktest.c:90:17: error: ‘SYS_clock_gettime64’ undeclared (first use in this function); did you mean ‘SYS_clock_gettime’?
   90 |         syscall(SYS_clock_gettime64, CLOCK_REALTIME, &ts);
      |                 ^~~~~~~~~~~~~~~~~~~
      |                 SYS_clock_gettime

The problem here is once again the changed behavior of the
__USE_TIME_BITS64 macro. Up to glibc 2.39 this was only set/defined when
building a compat application. So when time_t was "upgraded" from 4 to 8
bytes.

From glibc 2.40 onwards this macro will always be defined when time_t
is 8 bytes. So we basically run into the different code paths when
building 64 bit applications.

The reason for the compile error is that SYS_clock_gettime64() are only
provided by glibc when building compat applications.

Nice side effect: Should increase the support of libc implementations
where time_t is always 8 bytes, like musl.

The glibc commit that changed the behavior can be found at [1].

[1] https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=a4ed0471d71739928a0d0fa3258b3ff3b158e9b9;hp=a0698a5e92ceeed3409d28623b1d599da6bc887d

Signed-off-by: Florian Bezdeka <florian.bezdeka@siemens.com>
Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>