y2038: lib/cobalt: select: Fix compile failure observed on Debian 13
The following build failure was detected on Debian sid/trixie:

select.c: In function ‘do_select’:
select.c:55:23: error: implicit declaration of function ‘__real___select64’; did you mean ‘__real_select’? [-Wimplicit-function-declaration]
   55 |                 err = __STD(__select64(__nfds, __readfds, __writefds,
      |                       ^~~~~

The problem here is now the changed behavior of the __USE_TIME_BITS64
macro. Up to glibc 2.39 this was only set/defined when building a
compat application. So when time_t was "upgraded" from 4 to 8 bytes.

From glibc 2.40 onwards this macro will always be defined when time_t
is 8 bytes. So we basically run into the different code paths when
building 64 bit applications.

For the compat case we were missing the proper prototype produced
by COBALT_DECL_TIME64. The macro has been updated to address this
issue.

The glibc commit that changed the behavior can be found at [1].

[1] https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=a4ed0471d71739928a0d0fa3258b3ff3b158e9b9;hp=a0698a5e92ceeed3409d28623b1d599da6bc887d

Signed-off-by: Florian Bezdeka <florian.bezdeka@siemens.com>
Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>